import { Outfit } from 'next/font/google'
import './globals.css'
import Header from '@/Components/Header' // Ensure correct path
import Footer from '@/Components/Footer' // Ensure correct path

const outfit = Outfit({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})

export const metadata = {
  title: 'Blog App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${outfit.className} flex flex-col min-h-screen bg-[#fdf9f6]`}
      >
        <Header />
        <main className="flex-grow pt-20">{children}</main>
        <Footer />
      </body>
    </html>
  )
}
